---
application:
  name: "abou-apis"
  project: "abou"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "abou-db"
routers:
- name: "main-abou-apis"
  routes:
  - application_name: "abou-apis"
    paths:
    - "/*"
