---
application:
  name: "abou-apis"
  project: "abou-apis"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "aboud-db"
  version: "4.4"
routers:
- name: "main-abou-apis"
  routes:
  - application_name: "abou-apis"
    paths:
    - "/*"
